### ISSUE TITLE
Local configuration file or package.json property could not be found.

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#119]
I am using https://github.com/vega/vega-lite-dev-config/pull/481 with https://github.com/vega/vega-embed/pull/637 (using yarn link) and when I run yarn, I get this error

```
yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ beemo create-config

Local configuration file or package.json property could not be found.
    at ConfigLoader.loadConfig (/Users/dominik/Code/vega-embed/node_modules/@boost/core/lib/ConfigLoader.js:190:19)
    at Beemo.loadConfig (/Users/dominik/Code/vega-embed/node_modules/@boost/core/lib/Tool.js:394:41)
    at Beemo.initialize (/Users/dominik/Code/vega-embed/node_modules/@boost/core/lib/Tool.js:289:14)
    at new Beemo (/Users/dominik/Code/vega-embed/node_modules/@beemo/core/lib/Beemo.js:78:14)
    at Object.<anonymous> (/Users/dominik/Code/vega-embed/node_modules/@beemo/cli/lib/CLI.js:18:15)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by milesj** [comment]
@domoritz This looks like really old code since `@boost/core` doesn't exist anymore.

**Comment by domoritz** [comment]
It works if I prerelease a package but not with yarn link. Strange but unrelated to beemo.
