### ISSUE TITLE
Failed to resolve a path using the following lookups (in order):

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#129]
Check out https://github.com/vega/editor/commit/6f10c8601eba100df2348faea633b00ee6f9bdd9 and downgrade typescript to `~4.1.0`. 

Then run yarn

```
 ERROR

 Failed to resolve a path using the following lookups (in order):
   - @beemo/driver-typescript (NODE_MODULE)
   - beemo-driver-typescript (NODE_MODULE)
  [CMN:PATH_RESOLVE_LOOKUPS]

 STACK TRACE

CommonError: Failed to resolve a path using the following lookups (in order):
  - @beemo/driver-typescript (NODE_MODULE)
  - beemo-driver-typescript (NODE_MODULE)
 [CMN:PATH_RESOLVE_LOOKUPS]
    at PathResolver.resolve (/Users/dominik/Code/editor/node_modules/@boost/common/lib/PathResolver.js:85:13)
    at Loader.load (/Users/dominik/Code/editor/node_modules/@boost/plugin/lib/Loader.js:91:37)
    at Registry.load (/Users/dominik/Code/editor/node_modules/@boost/plugin/lib/Registry.js:139:34)
    at /Users/dominik/Code/editor/node_modules/@boost/plugin/lib/Registry.js:174:140
    at Array.map (<anonymous>)
    at Registry.loadMany (/Users/dominik/Code/editor/node_modules/@boost/plugin/lib/Registry.js:174:111)
    at Tool.bootstrap (/Users/dominik/Code/editor/node_modules/@beemo/core/lib/Tool.js:116:31)
    at async /Users/dominik/Code/editor/node_modules/@beemo/cli/lib/bin.js:30:5
    at async Program.run (/Users/dominik/Code/editor/node_modules/@beemo/cli/node_modules/@boost/cli/lib/Program.js:318:9)
    at async Program.runAndExit (/Users/dominik/Code/editor/node_modules/@beemo/cli/node_modules/@boost/cli/lib/Program.js:341:22)

error Command failed with exit code 1.
```

**Comment by milesj** [comment]
@domoritz Is this related to the Yarn stuff?

**Comment by domoritz** [comment]
I actually had this problem with yarn 1.
